#
# Copyright 2020 Somlabs
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += visionsom-8mm.o
obj-y += hw_config.o
ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += lpddr4_timing_MT53D512M32D2DS.o
obj-y += lpddr4_timing_K4F6E304HBMGCJ.o
obj-y += lpddr4_timing_MT53B256M32D1DS.o
obj-y += lpddr4_timing_MT53D1024M32D4DT.o
endif
