#
# Copyright 2024 Somlabs
#
# SPDX-License-Identifier:      GPL-2.0+
#

obj-y += visionsom-imx93.o
obj-y += hw_config.o

ifdef CONFIG_SPL_BUILD
obj-y += spl.o
obj-y += lpddr4_timing.o
obj-y += lpddr4_timing_2g.o
endif
